refs = {
    logo: document.querySelector('.site-logo'),
    header: document.querySelector('.header'),
    navLinkHome: document.querySelector('.home-js'),
    navLinkLibrary: document.querySelector('.library-js'),
    headerButtons: document.querySelector('.header-buttons'),
    burger: document.querySelector('.hamburger'),
    overlayHeader: document.querySelector('.overlay'),
    nav: document.querySelector('.page-nav'),
    searchForm: document.querySelector('.search-form'),
    siteNav: document.querySelector('.site-navigation'),
    buttonWatched: document.querySelector('.button-watched-js'),
    buttonQueue: document.querySelector('.button-queue-js'),
    buttonHomeOnBurger: document.querySelector('.site-navigation-on-burger__link-home-js'),
    buttonLibraryOnBurger: document.querySelector('.site-navigation-on-burger__link-library-js'),
    galleryList: document.querySelector('.list-films'),
    filmsSection: document.querySelector('.films-js'),
    filmViewSection: document.querySelector('.film-view-js'),
    pagination: document.querySelector('.pagination'),
    warningMessage: document.querySelector('.header-warning'),
    spiner: document.querySelector('.loader-overlay'),
    // fotoViewId: document.querySelector('.foto-img'),
    // addToWatch: document.querySelector('.film-view-buttons--watched'),
    addToQueue: document.querySelector('.film-view-buttons--queue')
}